import logging
from fastapi import APIRouter, HTTPException
from models.schemas import ResourceSchema, ResourcesResponse
from agents.resource_agent import ResourceAgent
from tools import storage

logger = logging.getLogger(__name__)
router = APIRouter()
_agent = ResourceAgent()


@router.get("/resources/{topic}", response_model=ResourcesResponse)
async def get_resources(topic: str, session_id: str):
    """
    Return personalized resources for a topic.

    Resources are generated by the ResourceAgent using the learner's level, goal,
    and weak areas, then cached in the agent (in-process) and in the session.
    """
    session = storage.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    topic_obj = next(
        (t for t in session.curriculum if t.id == topic or t.title.lower() == topic.lower()),
        None,
    )
    topic_id    = topic_obj.id    if topic_obj else topic
    topic_label = topic_obj.title if topic_obj else topic

    # Return session-cached resources if available (avoids AI call on page revisit)
    if topic_id in session.resources and session.resources[topic_id]:
        logger.info("Resources session-cache hit for topic '%s'", topic_id)
        raw_list = session.resources[topic_id]
        return ResourcesResponse(
            topic=topic_label,
            resources=[ResourceSchema(**r) for r in raw_list],
        )

    # Collect weak areas from quiz history for this topic
    quiz_weaknesses: list[str] = []
    for qr in session.quiz_results:
        if qr.topic_id == topic_id:
            quiz_weaknesses.extend(qr.weak_concepts)

    reflection_weaknesses: list[str] = []
    if topic_id in session.reflections:
        reflection_weaknesses = session.reflections[topic_id].get("weaknesses", [])

    raw_list = await _agent.recommend(
        topic=topic_label,
        level=session.level,
        goal=session.goal,
        quiz_weaknesses=quiz_weaknesses,
        reflection_weaknesses=reflection_weaknesses,
        topic_id=topic_id,
    )

    # Persist in session so revisits don't re-generate
    session.resources[topic_id] = raw_list
    storage.update_session(session)

    resources = [
        ResourceSchema(
            title=r["title"],
            url=r["url"],
            type=r["type"],
            source=r["source"],
            why=r["why"],
            duration=r.get("duration"),
            difficulty=r.get("difficulty"),
            category=r.get("category"),
        )
        for r in raw_list
    ]

    return ResourcesResponse(topic=topic_label, resources=resources)
